"""empty message

Revision ID: b556a9932953
Revises: 0e3af490c75f
Create Date: 2025-06-01 07:52:16.479847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b556a9932953'
down_revision = '0e3af490c75f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=120), nullable=False))
        batch_op.drop_column('lastname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###
